# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
env: ISISVER=3.6.1
#     - ISISVER=3.6.0
#     - ISISVER=3.6.1
#     - ISISVER=3.6.2


# Here we just install Miniconda, thanks to @astrofrog's example from astropy
before_install:
    - sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    # Install and activate ISIS:
    # - source activate test
    - conda config --add channels conda-forge
    - conda config --add channels usgs-astrogeology
    - conda config --show channels
    - conda create -q -n test python=$TRAVIS_PYTHON_VERSION
    - conda install -q -n test -c usgs-astrogeology isis3=$ISISVER
    - source activate test
    - python $CONDA_PREFIX/scripts/isis3VarInit.py --data-dir="$TRAVIS_BUILD_DIR/test-ISIS3DATA"
    - source activate test
    - conda info -a
    - python --version
    #- pip install -U tox-travis
    - pip install -U flake8

before_script:
    - make -B test-resources
    - ls test-ISIS3DATA
    - ls -la test-ISIS3DATA/base/translations/pdsImage.trn
    - pwd


# Command to run tests, e.g. python setup.py test
#script: tox
script:
    - flake8 kalasiris tests
#- python setup.py test
    - python setup.py test -s tests.test_kalasiris.Test_hi2isis


# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
# deploy:
#   provider: pypi
#   distributions: sdist bdist_wheel
#   user: rbeyer
#   password:
#     secure: PLEASE_REPLACE_ME
#   on:
#     tags: true
#     repo: rbeyer/kalasiris
#     python: 3.6
